spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sms_db?createDatabaseIfNotExist=true
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    jpa:
      repositories:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
